#!/bin/bash
#SBATCH -J Trimmomatic
#SBATCH --partition tres72
#SBATCH -o Trimmomatic_%j.txt
#SBATCH -e Trimmomatic_%j.err
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=32
#SBATCH --time=06:00:00

export OMP_NUM_THREADS=32

module purge
module load java/sunjdk_1.8.0
java -jar /share/apps/bioinformatics/trimmomatic/Trimmomatic-0.36/trimmomatic-0.36.jar \
PE \
/scrfs/storage/ytter/apple_raw_fastq/EL-Ly-80s-CODO-26_S18_R1_001.fastq.gz /scrfs/storage/ytter/apple_raw_fastq/EL-Ly-80s-CODO-26_S18_R2_001.fastq.gz \
/scrfs/storage/ytter/apple_raw_fastq/CODO-26_S18_1P_trim.fastq.gz /scrfs/storage/ytter/apple_raw_fastq/CODO-26_S18_1U_trim.fastq.gz \
/scrfs/storage/ytter/apple_raw_fastq/CODO-26_S18_2P_trim.fastq.gz /scrfs/storage/ytter/apple_raw_fastq/CODO-26_S18_2U_trim.fastq.gz \
ILLUMINACLIP:/share/apps/bioinformatics/trimmomatic/Trimmomatic-0.36/adapters/TruSeq3-PE.fa:2:30:10
